# -*- coding: utf-8 -*-
"""Aday federasyon domainleri. Probe ile dogrulanacak."""

CANDIDATES = {
 "futbol": ["tff.org"],
 "basketbol": ["tbf.org.tr", "basketbol.gov.tr"],
 "voleybol": ["tvf.org.tr", "voleybol.gov.tr"],
 "atletizm": ["taf.gov.tr", "taf.org.tr", "atletizm.gov.tr"],
 "hentbol": ["thf.gov.tr", "thf.org.tr", "hentbol.gov.tr"],
 "judo": ["judo.gov.tr", "tjf.gov.tr"],
 "gures": ["tgf.gov.tr", "gures.gov.tr"],
 "halter": ["halter.gov.tr", "thf.gov.tr"],
 "boks": ["boks.gov.tr", "tbf.gov.tr"],
 "taekwondo": ["taekwondo.gov.tr", "turkiyetaekwondofed.gov.tr"],
 "karate": ["karate.gov.tr", "tkf.gov.tr"],
 "yuzme": ["tyf.gov.tr", "yuzme.gov.tr"],
 "tenis": ["ttf.org.tr", "tenis.gov.tr"],
 "masatenisi": ["tmtf.gov.tr", "masatenisi.gov.tr"],
 "badminton": ["badminton.gov.tr", "tbf.gov.tr"],
 "bisiklet": ["bisiklet.gov.tr", "tbf.org.tr"],
 "okculuk": ["okculuk.gov.tr", "okcu.gov.tr"],
 "aticilik": ["aticilikavcilik.gov.tr", "taaf.gov.tr", "aticilik.gov.tr"],
 "binicilik": ["binicilik.gov.tr", "tbf.gov.tr"],
 "cimnastik": ["cimnastik.gov.tr", "tcf.gov.tr"],
 "eskrim": ["eskrim.gov.tr", "tef.gov.tr"],
 "kurek": ["kurek.gov.tr", "tkf.gov.tr"],
 "kano": ["kano.gov.tr", "tkf.gov.tr"],
 "yelken": ["tyf.org.tr", "yelken.gov.tr"],
 "triatlon": ["triatlon.gov.tr", "ttf.gov.tr"],
 "pentatlon": ["pentatlon.gov.tr", "tmpf.gov.tr", "modernpentatlon.gov.tr"],
 "buzsporlari": ["buzsporlari.gov.tr", "tbsf.gov.tr"],
 "kayak": ["kayak.gov.tr", "tkf.gov.tr"],
 "curling": ["curling.gov.tr", "tcf.gov.tr"],
 "dagcilik": ["tdf.gov.tr", "dagcilik.gov.tr"],
 "golf": ["tgf.org.tr", "golf.gov.tr"],
 "satranc": ["tsf.org.tr", "satranc.gov.tr"],
 "bric": ["tbrf.org.tr", "bric.gov.tr", "briç.gov.tr"],
 "bocce": ["bocce.gov.tr", "tbbdf.gov.tr"],
 "bilardo": ["bilardo.gov.tr", "tbf.gov.tr"],
 "motosiklet": ["tmf.org.tr", "motosiklet.gov.tr"],
 "otomobil": ["tosfed.org.tr"],
 "sualti": ["tssf.gov.tr", "tssf.org.tr", "sualti.gov.tr"],
 "vucutgelistirme": ["vucutgelistirme.gov.tr", "tvgf.gov.tr", "fitness.gov.tr"],
 "wushu": ["wushu.gov.tr", "twf.gov.tr"],
 "muaythai": ["muaythai.gov.tr", "tmf.gov.tr"],
 "kickboks": ["kickboks.gov.tr", "tkbf.gov.tr"],
 "bedenselengelliler": ["bedenselengelliler.gov.tr", "tbesf.org.tr", "tbesf.gov.tr"],
 "isitmeengelliler": ["isitmeengelliler.gov.tr", "tiesf.gov.tr", "tisf.gov.tr"],
 "gormeengelliler": ["gormeengelliler.gov.tr", "tgesf.gov.tr"],
 "ozelsporcular": ["tossfed.gov.tr", "ozelsporcular.gov.tr"],
 "herkesicinspor": ["herkesicinspor.gov.tr", "hisf.gov.tr", "thisf.gov.tr"],
 "geleneksel_guresler": ["tggf.org.tr", "tggf.gov.tr"],
 "halkoyunlari": ["thof.gov.tr", "halkoyunlari.gov.tr"],
 "hokey": ["hokey.gov.tr", "thf.gov.tr"],
 "beyzbol": ["tbsf.org.tr", "beyzbolsoftbol.gov.tr", "tbsf.gov.tr"],
 "ragbi": ["ragbi.gov.tr", "trf.gov.tr"],
 "oryantiring": ["oryantiring.gov.tr", "tof.gov.tr"],
 "universitesporlari": ["tusf.org.tr", "universitesporlari.gov.tr"],
 "okulsporlari": ["okulsportr.gov.tr", "okulsporlari.gov.tr", "tosf.gov.tr"],
 "danssporlari": ["tdsf.org.tr", "danssporlari.gov.tr"],
 "bilekguresi": ["bilekguresi.gov.tr", "tbgf.gov.tr"],
 "gelismekteolan": ["gosbf.org.tr", "gosb.gov.tr"],
 "amputefutbol": ["ampute.gov.tr", "tabff.gov.tr", "amputefutbol.gov.tr"],
 "tekerleklisandalyebasketbol": ["tsbf.gov.tr", "tekerleklisandalyebasketbol.gov.tr"],
 "havacilik": ["thk.org.tr", "thsf.gov.tr", "havacilik.gov.tr"],
 "korfbol": ["korfbol.gov.tr"],
 "sportirmanis": ["tdf.gov.tr"],
 "izcilik": ["tif.org.tr", "izcilik.gov.tr"],
 "gelisim": ["tgsf.gov.tr"],
 "paralimpik": ["paralimpik.org.tr", "tmpk.org.tr"],
 "olimpiyat": ["olimpiyat.org.tr"],
 "sporyazarlari": ["tsyd.org.tr"],
 "yamac": ["thk.org.tr"],
 "squash": ["squash.gov.tr", "tsf.gov.tr"],
 "tirmanis": ["tdf.org.tr"],
 "hava_sporlari": ["thsf.gov.tr"],
 "buzhokeyi": ["buzhokeyi.gov.tr"],
 "sportif_yetenek": [],
}
