# -*- coding: utf-8 -*-
"""Turkiye'deki spor federasyonlari (GSB bagimsiz federasyonlar + ozel kanunlu TFF + ust kuruluslar)."""

FEDERATIONS = [
    ("futbol", "Türkiye Futbol Federasyonu", ["futbol"]),
    ("basketbol", "Türkiye Basketbol Federasyonu", ["basketbol"]),
    ("voleybol", "Türkiye Voleybol Federasyonu", ["voleybol"]),
    ("atletizm", "Türkiye Atletizm Federasyonu", ["atletizm"]),
    ("hentbol", "Türkiye Hentbol Federasyonu", ["hentbol"]),
    ("judo", "Türkiye Judo Federasyonu", ["judo"]),
    ("gures", "Türkiye Güreş Federasyonu", ["güreş", "gures"]),
    ("halter", "Türkiye Halter Federasyonu", ["halter"]),
    ("boks", "Türkiye Boks Federasyonu", ["boks"]),
    ("taekwondo", "Türkiye Taekwondo Federasyonu", ["taekwondo"]),
    ("karate", "Türkiye Karate Federasyonu", ["karate"]),
    ("yuzme", "Türkiye Yüzme Federasyonu", ["yüzme", "yuzme"]),
    ("tenis", "Türkiye Tenis Federasyonu", ["tenis"]),
    ("masatenisi", "Türkiye Masa Tenisi Federasyonu", ["masa tenisi"]),
    ("badminton", "Türkiye Badminton Federasyonu", ["badminton"]),
    ("bisiklet", "Türkiye Bisiklet Federasyonu", ["bisiklet"]),
    ("okculuk", "Türkiye Okçuluk Federasyonu", ["okçuluk", "okculuk"]),
    ("aticilik", "Türkiye Atıcılık ve Avcılık Federasyonu", ["atıcılık", "aticilik"]),
    ("binicilik", "Türkiye Binicilik Federasyonu", ["binicilik"]),
    ("cimnastik", "Türkiye Cimnastik Federasyonu", ["cimnastik"]),
    ("eskrim", "Türkiye Eskrim Federasyonu", ["eskrim"]),
    ("kurek", "Türkiye Kürek Federasyonu", ["kürek", "kurek"]),
    ("kano", "Türkiye Kano Federasyonu", ["kano"]),
    ("yelken", "Türkiye Yelken Federasyonu", ["yelken"]),
    ("triatlon", "Türkiye Triatlon Federasyonu", ["triatlon"]),
    ("pentatlon", "Türkiye Modern Pentatlon Federasyonu", ["pentatlon"]),
    ("buzpateni", "Türkiye Buz Pateni Federasyonu", ["buz pateni"]),
    ("buzhokeyi", "Türkiye Buz Hokeyi Federasyonu", ["buz hokeyi"]),
    ("curling", "Türkiye Curling Federasyonu", ["curling"]),
    ("kayak", "Türkiye Kayak Federasyonu", ["kayak"]),
    ("dagcilik", "Türkiye Dağcılık Federasyonu", ["dağcılık", "dagcilik", "tırmanış"]),
    ("golf", "Türkiye Golf Federasyonu", ["golf"]),
    ("satranc", "Türkiye Satranç Federasyonu", ["satranç", "satranc"]),
    ("bric", "Türkiye Briç Federasyonu", ["briç", "bric"]),
    ("bocce", "Türkiye Bocce Bowling ve Dart Federasyonu", ["bocce", "bowling", "dart"]),
    ("bilardo", "Türkiye Bilardo Federasyonu", ["bilardo"]),
    ("motosiklet", "Türkiye Motosiklet Federasyonu", ["motosiklet"]),
    ("otomobil", "Türkiye Otomobil Sporları Federasyonu", ["otomobil"]),
    ("sualti", "Türkiye Sualtı Sporları Federasyonu", ["sualtı", "sualti", "su altı"]),
    ("vucutgelistirme", "Türkiye Vücut Geliştirme ve Fitness Federasyonu", ["vücut geliştirme", "fitness"]),
    ("wushu", "Türkiye Wushu Kung Fu Federasyonu", ["wushu"]),
    ("muaythai", "Türkiye Muaythai Federasyonu", ["muaythai", "muay thai"]),
    ("kickboks", "Türkiye Kick Boks Federasyonu", ["kick boks", "kickboks"]),
    ("bedenselengelliler", "Türkiye Bedensel Engelliler Spor Federasyonu", ["bedensel engelliler"]),
    ("isitmeengelliler", "Türkiye İşitme Engelliler Spor Federasyonu", ["işitme engelliler", "isitme engelliler"]),
    ("gormeengelliler", "Türkiye Görme Engelliler Spor Federasyonu", ["görme engelliler", "gorme engelliler"]),
    ("ozelsporcular", "Türkiye Özel Sporcular Spor Federasyonu", ["özel sporcular"]),
    ("herkesicinspor", "Türkiye Herkes İçin Spor Federasyonu", ["herkes için spor", "herkes icin spor"]),
    ("gelenekselguresler", "Türkiye Geleneksel Güreşler Federasyonu", ["geleneksel güreş"]),
    ("gelenekselsporlar", "Türkiye Geleneksel Spor Dalları Federasyonu", ["geleneksel spor dalları"]),
    ("halkoyunlari", "Türkiye Halk Oyunları Federasyonu", ["halk oyunları"]),
    ("hokey", "Türkiye Hokey Federasyonu", ["hokey"]),
    ("beyzbol", "Türkiye Beyzbol ve Softbol Federasyonu", ["beyzbol", "softbol", "korumalı futbol"]),
    ("ragbi", "Türkiye Ragbi Federasyonu", ["ragbi", "rugby"]),
    ("oryantiring", "Türkiye Oryantiring Federasyonu", ["oryantiring"]),
    ("universitesporlari", "Türkiye Üniversite Sporları Federasyonu", ["üniversite sporları"]),
    ("okulsporlari", "Türkiye Okul Sporları Federasyonu", ["okul sporları"]),
    ("danssporlari", "Türkiye Dans Sporları Federasyonu", ["dans sporları"]),
    ("bilekguresi", "Türkiye Bilek Güreşi Federasyonu", ["bilek güreşi"]),
    ("gelismekteolan", "Türkiye Gelişmekte Olan Spor Branşları Federasyonu", ["gelişmekte olan spor"]),
    ("amputefutbol", "Türkiye Ampute Futbol Federasyonu", ["ampute"]),
    ("tekerleklisandalyebasketbol", "Türkiye Tekerlekli Sandalye Basketbol Federasyonu", ["tekerlekli sandalye"]),
    ("havacilik", "Türk Hava Kurumu / Hava Sporları", ["hava sporları", "havacılık"]),
    ("korfbol", "Türkiye Korfbol Federasyonu", ["korfbol"]),
    ("sutopu", "Türkiye Su Topu Federasyonu", ["su topu", "sutopu"]),
    ("skateboard", "Türkiye Kaykay Federasyonu", ["kaykay", "skateboard"]),
    ("ekstremsporlar", "Türkiye Ekstrem Sporlar Federasyonu", ["ekstrem"]),
    ("shgm", "Spor Genel Müdürlüğü (Spor Hizmetleri)", ["spor genel müdürlüğü", "spor hizmetleri"]),
    ("gsb", "Gençlik ve Spor Bakanlığı", ["gençlik ve spor bakanlığı"]),
    ("tmok", "Türkiye Milli Olimpiyat Komitesi", ["olimpiyat komitesi"]),
    ("paralimpik", "Türkiye Milli Paralimpik Komitesi", ["paralimpik"]),
    ("sportoto", "Spor Toto Teşkilat Başkanlığı", ["spor toto"]),
]
